
import Head from 'next/head'
import HomeHero from '@/components/HomeHero'
import HomeBody from '@/components/HomeBody';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main className="bg-[#222A36]  w-screen">
<HomeHero />
<HomeBody/>
      </main>
    </>
  )
}
